_base_ : ['../base_text.yaml']

############## base differential #############

########### base differential ends ###########

############## dp differential #############
privc: 'gaussian_mechanism' # compressor name
sigma: 0 # noise multiplier * sensitivity = sigma
noise_multiplier: 1.0 # noise multiplier
# eps: 1.0 # epsilon
# delta: 1 / 10000 # delta <= 1/2N
########### dp differential ends ###########

use_dp: 1
# dp_mechanism: 'Laplace' # Laplace or Gaussian
