_base_ : ['../../defense/epfed.yaml']

############## base differential #############
num_users: 6000 # number of users: K
num_selected_users: 100 # number of selected users: 100, for shakespeare, it is 10
round: 180 # rounds of training
tau: 5
batch_size: 10 # local batch size
local_lr: 0.1 # local learning rate
local_momentum: 0.9 # SGD Momentum default 0.5
decay_weight: 0.999 # learning rate decay weight default 0.5
global_momentum: 0.9 # global momentum
clip: 1.0 # clipping threshold
########### base differential ends ###########

############# ep differential ################
noise_multiplier: 1.4 # noise multiplier
# com_p: 1.0 # compression ratio p = 1.0 implies no compression
############# ep differential ends############


# method: attack_defense_fedavg
method: fedavg_maskdp_all
# attack: agrAgnosticMinMax
# defend: signguard

# Model
# model: cnnfmnist

# Dataset configure
data_type: image
# dataset: fmnist
iid: 1 # whether i.i.d or not

# Attack method
# num_attackers: 10 # number of attackers